-- AP_TEST.SPORTS_TBL definition

CREATE TABLE `SPORTS_TBL` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `NAME` varchar(100) NOT NULL COMMENT 'Sports Name',
  PRIMARY KEY (`id`),
  UNIQUE KEY `SPORTS_TBL_UNIQUE` (`NAME`)
) ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;